name: 'Keil build'
description: 'Build keil project'
author: 'APS'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

# Define your inputs here.
inputs:
  project_name:
    description: 'Name of project'
    required: true
    default: ''

  target_name:
    description: 'Name of build target'
    required: true
    default: ''

runs:
  using: node20
  main: dist/index.js
